"""
Create demo data using Django Shell.

Usage:

python ./manage.py shell < tests/demo_data.py
"""

import random
import json
from lorem_text import lorem
from django.contrib.auth.models import Group, User
# from django.contrib.auth.hashers import make_password
from rest_framework.authtoken.models import Token
from ioc_management.models import (
    CodeSnippet,
    Event,
    FQDN,
    Hash,
    IpAdd,
    Vuln,
    CONFIDENCE_CHOICES,
    LANGUAGES,
    PLATFORM,
    VALIDATION_CHOICES,
)


# Drop data
Token.objects.all().delete()
Group.objects.all().delete()
User.objects.all().exclude(username="admin").delete()
Event.objects.all().delete()


def get_or_none(model, **kwargs):
    try:
        return model.objects.get(**kwargs)
    except model.DoesNotExist:
        pass
    return None


def get_choice(choices):
    choice = choices[random.randint(0, len(choices) - 1)]
    return choice[0]


USERS = [
    {"first_name": "Luca", "last_name": "Rinaldi"},
    {"first_name": "Giulia", "last_name": "Ferraro"},
    {"first_name": "Marco", "last_name": "Gentile"},
    {"first_name": "Sara", "last_name": "Colombo"},
    {"first_name": "Andrea", "last_name": "De Angelis"},
]

FIRMS = [
    "TechNova Solutions",
    "BlueWave Networks",
    "GreenLogic Systems",
]

EVENTS = [
    "Access Point Identified",
    "Access to Admin Panel",
    "Access to Analytics Platform",
    "Access to Secrets Vault",
    "Access to Source Control",
    "Access Token Reuse",
    "Access Violation",
    "Account Abuse",
    "Account Provisioning",
    "Actor Persistence Mechanism",
    "Actor Reconnaissance Activity",
    "Actor Tool Deployment",
    "Admin API Usage",
    "Adware Campaign",
    "API Keys Discovered",
    "API Token Generation",
    "Application Defacement",
    "Attack on Healthcare Network",
    "Attack",
    "Authentication Behavior",
    "Authentication Protocol Used",
    "Authentication Token Rotation",
    "Backup Credentials",
    "Backup Exposure",
    "Backup Restoration",
    "Backup Server",
    "Breach at Financial Institution",
    "Broken Object Level Authorization",
    "Browser Drive-By Download",
    "Browser Extension Found",
    "Browser Script Injection",
    "Campaign Discovered",
    "Certificate Authority",
    "Certificate Causing Exposure",
    "Certificate Issuance",
    "Chain Compromise Reported",
    "CI/CD Credentials",
    "Cloud API Calls",
    "Cloud Billing Anomaly",
    "Cloud Function Deployed",
    "Cloud Resource Creation",
    "Cloud Storage Access",
    "Code Execution Vulnerability",
    "Collaboration Platform",
    "Command and Control Communication",
    "Configuration Drift",
    "Container Escape",
    "Customer Support System",
    "Cybersecurity Incident Reported",
    "Data Archival Activity",
    "Data Compression Activity",
    "Data Exfiltration",
    "Data Theft",
    "Data Transfer Spike",
    "Data Warehouse Query",
    "Database Leak",
    "Database Query Activity",
    "Database Replication",
    "Denial of Service Attack",
    "Development Pipeline",
    "Device Compromise",
    "DNS Records",
    "Docker Image Found",
    "E-Commerce Platform",
    "Email Attachment",
    "Email Auto-Reply Rule",
    "Email Compromise Attempt",
    "Email Forwarding Campaign",
    "Email Forwarding Rule",
    "Email Server",
    "Embedded in Image File",
    "Encryption Keys",
    "Engineering Attack",
    "Escalation Exploit Used",
    "File Inclusion Vulnerability",
    "File Upload",
    "Fileless Attack Detected",
    "Firmware Backdoor",
    "Firmware Update",
    "Force Against VPN Gateway",
    "Force Login Attempts",
    "Geo-Location Login",
    "Harvesting Website Found",
    "Horse Detected",
    "HR System",
    "HTML Smuggling Attack",
    "Identity Compromise",
    "Identity Federation",
    "Identity Lifecycle Event",
    "Identity Provider",
    "Identity Role Change",
    "Identity Synchronization",
    "Improper Error Handling",
    "Inadequate Input Validation",
    "Infection in Corporate Network",
    "Infrastructure as Code Change",
    "Injection Vulnerability Found",
    "Injection Vulnerability",
    "Insecure Desktops",
    "Installation Detected",
    "Integrity Violation",
    "Intelligence Alert Triggered",
    "IT Security Risk Identified",
    "JavaScript Injection",
    "Kernel Module Detected",
    "Kit Activity Observed",
    "Lateral Movement Identified",
    "Leakage on Public Repository",
    "Leveraging Trusted Tools",
    "Log Deletion",
    "Logging Pipeline",
    "Logic Flaw Exploited",
    "Login Page Detected",
    "Loss Prevention Alert",
    "Macro Execution",
    "Malware Campaign",
    "Malware Detected",
    "Messaging Platform",
    "Misconfiguration Detected",
    "Misconfigured S3 Bucket",
    "Mobile Device Management",
    "Monitoring System",
    "Network Appliance",
    "Network Configuration Change",
    "Network Device Added",
    "Network Scan",
    "NPM Package Discovered",
    "OAuth Application",
    "OAuth Consent Phishing",
    "of API Rate Limit Bypass",
    "of Authentication Bypass",
    "of Broken Access Control",
    "of Default Credentials",
    "of Deserialization Bug",
    "of Insecure API Endpoint",
    "of Legacy System",
    "of Logging Bypass",
    "of Memory Corruption Bug",
    "of Misconfigured Load Balancer",
    "of Race Condition",
    "of Time-of-Check Flaw",
    "Open Redirect Vulnerability",
    "Password Reset",
    "Password Spray Attack",
    "Patch Failure",
    "Payment Processing System",
    "PDF Attachment",
    "Persistent Threat Activity",
    "Phishing Attack Reported",
    "Phishing Campaign",
    "Phishing via SMS",
    "PowerShell Execution",
    "Privilege Assignment",
    "Privilege Misuse",
    "Privileged Container",
    "Propagation via Network Shares",
    "Protection Failure",
    "QR Code Campaign",
    "Redirect Campaign",
    "Registry Modification",
    "Remote Desktop Access",
    "Residency Violation",
    "SaaS Application Access",
    "Scheduled Job",
    "Scheduled Task Created",
    "Scripting Attack Detected",
    "Security Breach",
    "Segmentation Bypass",
    "Service Account Login",
    "Service Account",
    "Service Installation",
    "Shell Detected on Server",
    "SIEM Configuration Change",
    "Sniffing Activity",
    "Software Update",
    "Source Code Access",
    "Spoofing Attack",
    "SSH Key Injection",
    "Storage Misconfiguration Exposed Data",
    "Stuffing Attack Identified",
    "Tampering Discovered",
    "Theft Attempt",
    "Threat Detected",
    "Token Abuse Detected",
    "Token Replay Attack",
    "Traffic Anomaly",
    "Traffic Surge Observed",
    "USB Device Used",
    "Using Encrypted Payloads",
    "Using Living-off-the-Land Techniques",
    "Vendor Breach",
    "VPN Login Detected",
    "Vulnerability Disclosure",
    "Vulnerability Exploited",
    "Weak Encryption",
    "Weak Password Policy",
    "Weak Session Management",
    "Webhook Activity",
]

CODESNIPPETS = [
    "APT Backdoor Initializer",
    "APT C2 Loader Example",
    "APT Lateral Movement Demo",
    "APT Lateral Movement PoC",
    "APT Lateral Movement Script",
    "APT Malware C2 Simulation",
    "APT Malware Loader Demo",
    "APT Malware Sample for Demo",
    "APT Malware Simulation",
    "Backdoor C2 Communication",
    "Backdoor Installation Example",
    "Backdoor Installation Script",
    "Backdoor via Cron in Linux",
    "Backdoor via Scheduled Task",
    "Backdoor via Scheduled Task",
    "Base64 Encoded Malware Loader",
    "Bash Reverse TCP Shell",
    "Browser Exploit Demo Script",
    "Browser Exploit Demo Script",
    "Browser Exploit Demo",
    "Browser Exploit Loader",
    "Browser Exploit PoC",
    "Browser Extension Malware Stub",
    "Browser Loader Script Example",
    "Browser Malware Loader Demo",
    "Buffer Overflow in Image Processing",
    "C2 Beacon Demo Script",
    "C2 Beacon over HTTP",
    "C2 Beacon PowerShell Demo",
    "C2 Beaconing PowerShell",
    "C2 Communication PoC",
    "Command and Control Beacon Sample",
    "Command Execution in Node.js",
    "Command Injection Exploit",
    "Command Injection in File Upload",
    "Command Injection via Curl",
    "Command Injection via Python",
    "Credential Dumping Script",
    "Credential Harvester VBA Macro",
    "Credential Harvester via HTML Form",
    "Credential Harvesting Demo",
    "Credential Harvesting HTML Form",
    "Credential Harvesting Script",
    "Credential Harvesting Script",
    "Cron Job Malicious Loader",
    "Cron Job Malware Demo",
    "Cron Job Persistence Example",
    "Cron Malware Loader",
    "Cross-Site Request Forgery Demo",
    "Cross-Site Scripting (XSS) in Search Form",
    "Crypto Miner Embedded in JS",
    "Cryptojacking JS Miner",
    "Cryptojacking Script Injection",
    "CVE Exploit Simulation",
    "CVE-2020-XXXX Exploit",
    "CVE-2022-XXXX Exploit Sample",
    "DLL Hijack Example",
    "DLL Hijacking Demonstration",
    "DLL Injection Demo",
    "DLL Injection Malware Demo",
    "DLL Injection PoC",
    "DLL Injection via rundll32",
    "DLL Side-Loading Demonstration",
    "DLL Side-Loading Sample",
    "DNS Exfiltration Proof of Concept",
    "DNS Tunneling Payload",
    "Email Phishing Attachment Macro",
    "Encoded Bash Reverse Shell Example",
    "Encoded Bash Reverse Shell",
    "Encoded Bash Reverse TCP Shell",
    "Encoded Linux Reverse Shell",
    "Encoded Malware for Testing",
    "Encoded Malware Loader",
    "Encoded PowerShell C2 Demo",
    "Encoded PowerShell Download",
    "Encoded PowerShell for C2",
    "Encoded PowerShell Loader",
    "Encoded PowerShell Payload",
    "Encoded PowerShell RAT",
    "Exfiltrate Files via Email",
    "Exfiltration Script via HTTP",
    "Exfiltration Using HTTP POST",
    "Exfiltration via HTTP Request",
    "Exploit for Apache Struts CVE",
    "Exploit for CVE-2021-XXXX",
    "Exploit for CVE-2023-XXXX",
    "Exploit for Node.js Vulnerability",
    "Exploit for PHP Object Injection",
    "Exploit Kit Landing Page",
    "Exploit via HTTP Header Injection",
    "Fake Login Credential Collector",
    "Fake Login Credential Harvester",
    "Fake Login Credential Harvesting",
    "Fake Login HTML Demo",
    "Fake Login HTML Form",
    "Fake Login Page for Demo",
    "Fake Login Portal Demo",
    "Fake Login Portal HTML Template",
    "Fake Update Loader PoC",
    "Fake Update Malware Demo",
    "Fake Update Malware Stub",
    "Fake Update Notification Demo",
    "Fake Update Notification HTML",
    "Fake Update Script",
    "Fileless Malware via WMI",
    "FTP Brute Force Example",
    "HTTP Beaconing Script Example",
    "IoT Device Exploit Script",
    "IoT Exploit Script Demo",
    "IoT Malware Propagation Example",
    "IoT Malware Stub",
    "Java Deserialization Exploit",
    "JavaScript Credential Grabber",
    "JavaScript RAT Payload",
    "Keylogger in AutoHotkey",
    "Keylogger Macro Demo",
    "Keylogger Macro PoC",
    "Keylogger Macro Script",
    "Keylogger Payload Demo",
    "Keylogger Python Script Demo",
    "Keylogger via AutoHotkey Demo",
    "Keylogger via AutoIT",
    "Keylogger via JavaScript",
    "Linux Cron Job Persistence",
    "Linux Privilege Escalation PoC",
    "Linux Privilege Escalation Script",
    "Linux Reverse Shell Demo",
    "Linux Reverse Shell PoC",
    "Linux Rootkit Loader Example",
    "Linux Rootkit Loader",
    "Macro-Enabled Excel Downloader",
    "Malicious Android APK Stub",
    "Malicious Android Intent Payload",
    "Malicious Bash Script Example",
    "Malicious Chrome Extension Example",
    "Malicious Chrome Extension Loader",
    "Malicious Chrome Extension PoC",
    "Malicious Email Attachment Demo",
    "Malicious Excel Macro Example",
    "Malicious Excel Macro",
    "Malicious HTML Form",
    "Malicious JavaScript File",
    "Malicious Macro for Excel 4.0",
    "Malicious Macro Word 97-2003",
    "Malicious Macro Word Document",
    "Malicious PDF Embedded Script",
    "Malicious PowerShell Download Script",
    "Malicious Python Loader",
    "Malicious Python Script Example",
    "Malicious Shell Script for Linux",
    "Malicious VBA Macro Example",
    "Malicious YAML Config Payload",
    "Malware Auto-Execution Script",
    "Malware Command Execution Example",
    "Malware Command Execution",
    "Malware Command Parser",
    "Malware Dropper Bash Script",
    "Malware Dropper Example",
    "Malware Dropper in VBScript",
    "Malware Dropper PoC",
    "Malware Dropper via Certutil",
    "Malware Dropping Script",
    "Malware Exfiltration Demo",
    "Malware Exfiltration via Email",
    "Malware Loader Using Certutil",
    "Malware Loader via Certutil Demo",
    "Malware Loader via mshta Example",
    "Malware Loader via mshta",
    "Malware Persistence via Startup Folder",
    "Malware Stub for Testing",
    "Memory Corruption Exploit PoC",
    "Memory Dumping Tool Malicious Example",
    "Memory Injection Example",
    "Memory Injection PoC",
    "Node.js Reverse TCP Shell",
    "Obfuscated Bash Loader",
    "Obfuscated Bash One-Liner",
    "Obfuscated JavaScript for Browser Exploit",
    "Obfuscated JavaScript Loader",
    "Obfuscated JavaScript Payload",
    "Obfuscated Macro in Word",
    "Obfuscated Macro VBA Downloader",
    "Obfuscated PHP Backdoor",
    "Obfuscated PHP Downloader",
    "Obfuscated PHP Loader Example",
    "Obfuscated PHP Malware",
    "Obfuscated PHP Web Shell",
    "Obfuscated Python C2 Client",
    "Obfuscated Python Downloader",
    "Obfuscated Python Downloader",
    "Obfuscated Python Malware",
    "Obfuscated Python RAT Loader",
    "Obfuscated Python RAT",
    "Obfuscated Shell Command Injection",
    "Obfuscated VBA Downloader",
    "Obfuscated VBA Macro Loader",
    "Obfuscated VBScript Downloader",
    "Obfuscated VBScript Payload",
    "Phishing Email Template",
    "Phishing Email with Link",
    "Phishing Landing Page Demo",
    "Phishing Landing Page Template",
    "Phishing Page HTML Template",
    "PowerShell Beacon Demo",
    "PowerShell RAT Loader",
    "Privilege Escalation PoC Windows",
    "Privilege Escalation via Sudo",
    "Privilege Escalation via SUID Binary",
    "Python Downloader Script",
    "Python Keylogger Script",
    "Python Memory Dump Script",
    "Python Reverse Shell over HTTP",
    "Ransomware Encryption Routine Demo",
    "Ransomware Encryption Script",
    "Ransomware File Encryption Demo",
    "Ransomware File Encryption Routine",
    "Ransomware Key Generation PoC",
    "Ransomware Key Generation Script",
    "Ransomware Keygen PoC",
    "Ransomware Simulation Script",
    "RAT Client Example",
    "RAT Command Parser Example",
    "RAT Communication Example",
    "RAT Loader via HTTPS Demo",
    "RAT Payload Delivery Script",
    "RAT Payload over HTTPS",
    "RDP Brute Force Automation",
    "RDP Brute Force PoC",
    "Remote Access Trojan Loader",
    "Remote Desktop Access Automation",
    "Remote Desktop Access Malware",
    "Remote File Inclusion via URL Parameter",
    "Remote Shell over HTTPS",
    "Remote Shell via Netcat Listener",
    "Remote Shell via Netcat",
    "Reverse Shell in Bash",
    "Reverse Shell in JavaScript",
    "Reverse Shell PoC Windows",
    "Reverse Shell using Python Socket",
    "Reverse Shell using Python Socket",
    "Reverse Shell via Bash One-Liner",
    "Reverse Shell via Bash",
    "Reverse Shell via Netcat Demo",
    "Reverse Shell via Netcat Listener",
    "Reverse Shell via Node.js",
    "Reverse Shell via PHP",
    "Reverse Shell via TCP Demo",
    "Reverse Shell via TCP Socket",
    "Reverse TCP Shell Demo",
    "Reverse TCP Shell for Windows",
    "Reverse TCP Shell in Node.js",
    "Reverse TCP Shell in Python",
    "ROP Chain Demonstration",
    "Shellcode Injection Example",
    "SMB Exploit Sample",
    "SQL Injection - Login Bypass",
    "SSH Brute Force Automation",
    "Stealer Script for Cookies",
    "Steganography Data Exfiltration",
    "Steganography Payload Example",
    "Trojan Downloader Example",
    "Unauthorized File Access Script",
    "Web Form Input Exploit",
    "Web Shell File Manager",
    "Web Shell Upload Payload",
    "Web Shell with File Upload",
    "Windows PowerShell Script Example",
    "Windows Registry Persistence Script",
    "Windows Service Exploit Example",
    "Windows Service Persistence Demo",
    "Windows Service Persistence PoC",
    "Windows Service Persistence Script",
    "Windows Task Scheduler Exploit",
    "Windows Task Scheduler Exploit",
    "Worm Propagation Script",
]

FQDNS = [
    "api081.service.io",
    "api082.service.io",
    "api083.service.io",
    "api084.service.io",
    "api085.service.io",
    "api086.service.io",
    "api087.service.io",
    "api088.service.io",
    "api089.service.io",
    "api090.service.io",
    "api091.service.io",
    "api092.service.io",
    "api093.service.io",
    "api094.service.io",
    "api095.service.io",
    "api096.service.io",
    "api097.service.io",
    "api098.service.io",
    "api099.service.io",
    "api100.service.io",
    "backup181.storage.cloud",
    "backup182.storage.cloud",
    "backup183.storage.cloud",
    "backup184.storage.cloud",
    "backup185.storage.cloud",
    "backup186.storage.cloud",
    "backup187.storage.cloud",
    "backup188.storage.cloud",
    "backup189.storage.cloud",
    "backup190.storage.cloud",
    "backup191.storage.cloud",
    "backup192.storage.cloud",
    "backup193.storage.cloud",
    "backup194.storage.cloud",
    "backup195.storage.cloud",
    "backup196.storage.cloud",
    "backup197.storage.cloud",
    "backup198.storage.cloud",
    "backup199.storage.cloud",
    "backup200.storage.cloud",
    "db101.internal.lan",
    "db102.internal.lan",
    "db103.internal.lan",
    "db104.internal.lan",
    "db105.internal.lan",
    "db106.internal.lan",
    "db107.internal.lan",
    "db108.internal.lan",
    "db109.internal.lan",
    "db110.internal.lan",
    "db111.internal.lan",
    "db112.internal.lan",
    "db113.internal.lan",
    "db114.internal.lan",
    "db115.internal.lan",
    "db116.internal.lan",
    "db117.internal.lan",
    "db118.internal.lan",
    "db119.internal.lan",
    "db120.internal.lan",
    "edge161.network.edge",
    "edge162.network.edge",
    "edge163.network.edge",
    "edge164.network.edge",
    "edge165.network.edge",
    "edge166.network.edge",
    "edge167.network.edge",
    "edge168.network.edge",
    "edge169.network.edge",
    "edge170.network.edge",
    "edge171.network.edge",
    "edge172.network.edge",
    "edge173.network.edge",
    "edge174.network.edge",
    "edge175.network.edge",
    "edge176.network.edge",
    "edge177.network.edge",
    "edge178.network.edge",
    "edge179.network.edge",
    "edge180.network.edge",
    "host001.example.com",
    "host002.example.com",
    "host003.example.com",
    "host004.example.com",
    "host005.example.com",
    "host006.example.com",
    "host007.example.com",
    "host008.example.com",
    "host009.example.com",
    "host010.example.com",
    "host011.example.com",
    "host012.example.com",
    "host013.example.com",
    "host014.example.com",
    "host015.example.com",
    "host016.example.com",
    "host017.example.com",
    "host018.example.com",
    "host019.example.com",
    "host020.example.com",
    "host021.example.net",
    "host022.example.net",
    "host023.example.net",
    "host024.example.net",
    "host025.example.net",
    "host026.example.net",
    "host027.example.net",
    "host028.example.net",
    "host029.example.net",
    "host030.example.net",
    "host031.example.net",
    "host032.example.net",
    "host033.example.net",
    "host034.example.net",
    "host035.example.net",
    "host036.example.net",
    "host037.example.net",
    "host038.example.net",
    "host039.example.net",
    "host040.example.net",
    "mail121.domain.com",
    "mail122.domain.com",
    "mail123.domain.com",
    "mail124.domain.com",
    "mail125.domain.com",
    "mail126.domain.com",
    "mail127.domain.com",
    "mail128.domain.com",
    "mail129.domain.com",
    "mail130.domain.com",
    "mail131.domain.com",
    "mail132.domain.com",
    "mail133.domain.com",
    "mail134.domain.com",
    "mail135.domain.com",
    "mail136.domain.com",
    "mail137.domain.com",
    "mail138.domain.com",
    "mail139.domain.com",
    "mail140.domain.com",
    "node141.cluster.dev",
    "node142.cluster.dev",
    "node143.cluster.dev",
    "node144.cluster.dev",
    "node145.cluster.dev",
    "node146.cluster.dev",
    "node147.cluster.dev",
    "node148.cluster.dev",
    "node149.cluster.dev",
    "node150.cluster.dev",
    "node151.cluster.dev",
    "node152.cluster.dev",
    "node153.cluster.dev",
    "node154.cluster.dev",
    "node155.cluster.dev",
    "node156.cluster.dev",
    "node157.cluster.dev",
    "node158.cluster.dev",
    "node159.cluster.dev",
    "node160.cluster.dev",
    "srv041.corp.local",
    "srv042.corp.local",
    "srv043.corp.local",
    "srv044.corp.local",
    "srv045.corp.local",
    "srv046.corp.local",
    "srv047.corp.local",
    "srv048.corp.local",
    "srv049.corp.local",
    "srv050.corp.local",
    "srv051.corp.local",
    "srv052.corp.local",
    "srv053.corp.local",
    "srv054.corp.local",
    "srv055.corp.local",
    "srv056.corp.local",
    "srv057.corp.local",
    "srv058.corp.local",
    "srv059.corp.local",
    "srv060.corp.local",
    "web061.company.org",
    "web062.company.org",
    "web063.company.org",
    "web064.company.org",
    "web065.company.org",
    "web066.company.org",
    "web067.company.org",
    "web068.company.org",
    "web069.company.org",
    "web070.company.org",
    "web071.company.org",
    "web072.company.org",
    "web073.company.org",
    "web074.company.org",
    "web075.company.org",
    "web076.company.org",
    "web077.company.org",
    "web078.company.org",
    "web079.company.org",
    "web080.company.org",
]

with open('tests/ioc_management/nist-cves.json', 'r') as fh:
    vulns_data = fh.read()
    VULNS = json.loads(vulns_data)['vulnerabilities']


# Create superuser
admin_obj = get_or_none(User, username="admin")
if not admin_obj:
    admin_obj = User.objects.create_superuser(
        username="admin", password="admin", email="admin@example.com"
    )
    admin_obj.full_clean()


# Create groups
group_list = []
for firm in FIRMS:
    group = Group.objects.create(name=firm)
    group.full_clean()
    group_list.append(group)


# Create users
user_list = []
# password_hash = make_password("password")
password_hash = "pbkdf2_sha256$1000000$eF2L5tYyTWTEro6dJaU9HS$n7JgU23uuRDpd+6ko7Zpd+UYpdRQhFLw9gvu945iGCU="
for user in USERS:
    username = (
        f'{user["first_name"][0]}{user["last_name"]}'.replace("'", "")
        .replace(" ", "")
        .lower()
    )
    role_id = random.randint(0, 2)
    is_admin = True if role_id == 0 else False
    is_staff = True if is_admin or role_id == 1 else False
    is_active = bool(random.randint(0, 1))
    payload = {
        "username": username,
        "first_name": user["first_name"],
        "last_name": user["last_name"],
        "email": f"{username}@example.com",
        "is_superuser": is_admin,
        "is_staff": is_staff,
        "is_active": is_active,
        "password": password_hash,
    }
    user_obj = User.objects.create(**payload)
    user_obj.full_clean()
    user_list.append(user_obj)
    Token.objects.create(user=user_obj)
    groups_obj = []
    for _ in range(0, 3):
        firm_id = random.randint(0, len(FIRMS) - 1)
        groups_obj.append(Group.objects.get(name=FIRMS[firm_id]))
    user_obj.groups.set(groups_obj)
    user_obj.save()


# Create events
event_list = []
for user_obj in user_list:
    for _ in range(0, 10):
        event_id = random.randint(0, len(EVENTS) - 1)
        payload = {
            "author_id": user_obj.id,
            "description": lorem.paragraphs(3).replace("\n", "\n\n"),
            "name": EVENTS.pop(event_id),
        }
        event_obj = Event.objects.create(**payload)
        event_obj.full_clean()
        event_list.append(event_obj)

        # Add Code Snippet
        for _ in range(0, random.randint(0, 5)):
            codesnippet_id = random.randint(0, len(CODESNIPPETS) - 1)
            payload = {
                "author_id": user_obj.id,
                "code": lorem.paragraphs(3).replace("\n", "\n\n"),
                "confidence": get_choice(CONFIDENCE_CHOICES),
                "description": lorem.paragraphs(2).replace("\n", "\n\n"),
                "event_id": str(event_obj.id),
                "language": get_choice(LANGUAGES),
                "name": CODESNIPPETS.pop(codesnippet_id),
                "validation_status": get_choice(VALIDATION_CHOICES),
            }
            attribute_obj = CodeSnippet.objects.create(**payload)
            attribute_obj.full_clean()

        # Add FQDN
        for _ in range(0, random.randint(0, 5)):
            fqdn_id = random.randint(0, len(FQDNS) - 1)
            payload = {
                "author_id": user_obj.id,
                "confidence": get_choice(CONFIDENCE_CHOICES),
                "description": lorem.paragraphs(2).replace("\n", "\n\n"),
                "event_id": str(event_obj.id),
                "fqdn": FQDNS.pop(fqdn_id),
                "ip_address": f"{random.randint(1, 200)}.{random.randint(1, 200)}.{random.randint(1, 200)}.{random.randint(1, 200)}",
                "validation_status": get_choice(VALIDATION_CHOICES),
            }
            attribute_obj = FQDN.objects.create(**payload)
            attribute_obj.full_clean()

        # Add Vuln
        for _ in range(0, random.randint(0, 5)):
            vuln_id = random.randint(0, len(VULNS) - 1)
            cve = VULNS.pop(vuln_id)['cve']
            if 'metrics' in cve and cve['metrics'].values():
                cvss = float(list(cve['metrics'].values())[0][0]['cvssData']['baseScore'])
            else:
                cvss = 0
            payload = {
                "author_id": user_obj.id,
                "cve": cve['id'],
                "cvss": float(cvss),
                "description": lorem.paragraphs(2).replace("\n", "\n\n"),
                "event_id": str(event_obj.id),
                "name": cve['id'],
            }
            attribute_obj = Vuln.objects.create(**payload)
            attribute_obj.full_clean()
