# Generated by Django 4.2.16 on 2025-11-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=32, unique=True)),
                ('api_url', models.CharField(max_length=128)),
                ('api_key', models.CharField(max_length=128)),
                ('api_verify_cert', models.BooleanField(default=True)),
                ('api_timeout', models.IntegerField(default=10)),
                ('api_description', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('author', models.CharField(default=None, editable=False, max_length=32, null=True)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '01 :: API Configuration',
                'verbose_name_plural': '01 :: API Configurations',
            },
        ),
        migrations.CreateModel(
            name='BaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=32, unique=True)),
                ('param_value', models.CharField(max_length=128)),
                ('param_description', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('author', models.CharField(default=None, editable=False, max_length=32, null=True)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32, null=True)),
            ],
            options={
                'verbose_name': '00 :: Base Configuration',
                'verbose_name_plural': '00 :: Base Configurations',
            },
        ),
    ]
