from django.db import models
import uuid

#############################################################################
# HttpLog
#############################################################################


class HttpLog(models.Model):
    """
    Model for HTTP honeypot.
    """

    author = models.CharField(max_length=32, editable=False, default=None)
    lastchange_author = models.CharField(max_length=32, editable=False, default=None)
    log_date = models.DateField(auto_now=False, auto_now_add=True)
    req_body = models.TextField(blank=True, default="none")
    req_header = models.TextField(blank=True, default="none")  # full header
    req_path = models.CharField(max_length=256, unique=False)  # path requested
    req_type = models.CharField(max_length=32, unique=False)  # GET, POST, HEAD
    req_useragent = models.CharField(max_length=256)
    req_xff = models.GenericIPAddressField(unpack_ipv4=True)  # X-Forwarded-For
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Database metadata."""

        db_table = "http_log"
        ordering = ("-created_at",)
        verbose_name = "01 :: HTTP Honeypot"
        verbose_name_plural = "01 :: HTTP Honeypot"


#############################################################################
# TelnetLog
#############################################################################


class TelnetLog(models.Model):
    """
    Model for Telnet honeypot.
    """

    author = models.CharField(max_length=32, editable=False, default=None)
    lastchange_author = models.CharField(max_length=32, editable=False, default=None)
    log_date = models.DateField(auto_now=False, auto_now_add=True)
    req_command = models.TextField(blank=True, default="none")  # command executed
    req_ip = models.GenericIPAddressField(unpack_ipv4=True)  # IP address
    req_password = models.CharField(max_length=64, unique=False)  # password
    req_port = models.IntegerField()  # Port
    req_username = models.CharField(max_length=64, unique=False)  # username
    session_id = models.CharField(
        max_length=64, unique=True, default=uuid.uuid4
    )  # session ID (unique) random generated by uuid (ex: '550e8400-e29b-41d4-a716-446655440000')
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Database metadata."""

        db_table = "telnet_log"
        ordering = ("-created_at",)
        verbose_name = "02 :: Telnet Honeypot"
        verbose_name_plural = "02 :: Telnet Honeypot"
