# Generated by Django 4.2.16 on 2024-12-22 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='end_of_life',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 20, 46, 28, 903032, tzinfo=datetime.timezone.utc)),
        ),
    ]
