# Generated by Django 4.2.16 on 2024-12-23 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infosec_dashboard', '0005_alter_asset_end_of_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='end_of_life',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
