# Generated by Django 5.2.7 on 2025-12-23 10:02

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '00 :: Event',
                'verbose_name_plural': '00 :: Events',
                'db_table': 'event',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64)),
                ('description', models.TextField()),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2026, 1, 22, 10, 2, 48, 134005, tzinfo=datetime.timezone.utc))),
                ('language', models.CharField(choices=[('bash', 'Bash'), ('cmd', 'CMD'), ('powershell', 'PowerShell'), ('python', 'Python')], default='python', max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('validation_status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codesnippets', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_codesnippets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codesnippets', to='ioc_management.event')),
            ],
            options={
                'verbose_name': '03 :: Code Snippet',
                'verbose_name_plural': '03 :: Code Snippets',
                'db_table': 'codesnippet',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FQDN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64)),
                ('description', models.TextField()),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2026, 1, 22, 10, 2, 48, 134399, tzinfo=datetime.timezone.utc))),
                ('fqdn', models.CharField(max_length=64)),
                ('validation_status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fqdns', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_fqdns', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fqdns', to='ioc_management.event')),
            ],
            options={
                'verbose_name': '04 :: FQDN',
                'verbose_name_plural': '04 :: FQDNs',
                'db_table': 'fqdn',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64)),
                ('filename', models.CharField(blank=True, max_length=64, null=True)),
                ('md5', models.CharField(blank=True, max_length=64, null=True)),
                ('platform', models.CharField(choices=[('linux', 'Linux'), ('macos', 'MacOS'), ('windows', 'Windows')], default='windows', max_length=64)),
                ('sha1', models.CharField(blank=True, max_length=64, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, max_length=64, null=True)),
                ('description', models.TextField()),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2026, 1, 22, 10, 2, 48, 134962, tzinfo=datetime.timezone.utc))),
                ('validation_status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashes', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_hashes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashes', to='ioc_management.event')),
            ],
            options={
                'verbose_name': '05 :: File Hash',
                'verbose_name_plural': '05 :: File Hashes',
                'db_table': 'hashes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IpAdd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64)),
                ('description', models.TextField()),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2026, 1, 22, 10, 2, 48, 133365, tzinfo=datetime.timezone.utc))),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('validation_status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipadds', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_ipadds', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipadds', to='ioc_management.event')),
            ],
            options={
                'verbose_name': '02 :: IP Address',
                'verbose_name_plural': '02 :: IP Addresses',
                'db_table': 'ipadd',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='none', max_length=64, unique=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_reviews', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ioc_management.event')),
            ],
            options={
                'verbose_name': '06 :: IoC Review',
                'verbose_name_plural': '06 :: IoC Reviews',
                'db_table': 'reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve', models.CharField(max_length=64)),
                ('cvss', models.FloatField()),
                ('description', models.TextField()),
                ('exploitation_details', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulns', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_vulns', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='ioc_management.event')),
            ],
            options={
                'verbose_name': '01 :: Vulnerability',
                'verbose_name_plural': '01 :: Vulnerabilities',
                'db_table': 'vuln',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploits', to=settings.AUTH_USER_MODEL)),
                ('contributors_authors', models.ManyToManyField(editable=False, related_name='contributed_exploits', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploits', to='ioc_management.event')),
                ('vuln', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exploits', to='ioc_management.vuln')),
            ],
            options={
                'verbose_name': '07 :: Exploit',
                'verbose_name_plural': '07 :: Exploits',
                'db_table': 'exploits',
                'ordering': ('-updated_at',),
            },
        ),
    ]
