# Generated by Django 4.2.16 on 2024-12-22 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='none', max_length=56)),
                ('platform', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('macOS', 'macOS')], default='Windows', max_length=16)),
                ('sha256', models.TextField()),
                ('sha1', models.TextField()),
                ('md5', models.TextField()),
                ('website', models.URLField(blank=True, default='none', max_length=50)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=16)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(default=datetime.datetime(2024, 12, 22, 20, 43, 53, 880682, tzinfo=datetime.timezone.utc))),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ipadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, unpack_ipv4=True)),
                ('url', models.CharField(blank=True, default='none', max_length=32)),
                ('fqdn', models.CharField(blank=True, default='none', max_length=32)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=16)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(default=datetime.datetime(2024, 12, 22, 20, 43, 53, 880489, tzinfo=datetime.timezone.utc))),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('cvss', models.FloatField(default=0, null=True)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='VulnReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(default='none', max_length=64, unique=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('references_url', models.CharField(blank=True, max_length=256, null=True)),
                ('exploit_url', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
                ('cve_name', models.OneToOneField(db_column='name', default='none', on_delete=django.db.models.deletion.CASCADE, related_name='cve_review', to='ioc_management.vuln', to_field='name')),
            ],
        ),
    ]
