# Generated by Django 5.2.7 on 2025-12-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='exploit',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='hash',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='ipadd',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='vuln',
            old_name='contributors_authors',
            new_name='contributors',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=64),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=64),
        ),
        migrations.AlterField(
            model_name='hash',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=64),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=64),
        ),
    ]
