# Generated by Django 5.2.7 on 2025-12-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0002_rename_contributors_authors_codesnippet_contributors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdn',
            name='fqdn',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='hash',
            name='filename',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hash',
            name='md5',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha1',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cve',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
