# Generated by Django 5.2.7 on 2025-12-23 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0002_alter_codesnippet_expire_date_alter_fqdn_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 8, 53, 41, 868430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 8, 53, 41, 868430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hash',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 8, 53, 41, 868430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 8, 53, 41, 868430, tzinfo=datetime.timezone.utc)),
        ),
    ]
