# Generated by Django 4.2.16 on 2024-12-23 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0004_alter_hash_expire_date_alter_ipadd_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 23, 0, 3, 11, 342800, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 23, 0, 3, 11, 342616, tzinfo=datetime.timezone.utc)),
        ),
    ]
