# Generated by Django 4.2.16 on 2024-12-23 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0005_alter_hash_expire_date_alter_ipadd_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='expire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
