# Generated by Django 4.2.16 on 2024-12-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0007_ipaddreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='sha256',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='HashReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(default='none', max_length=64, unique=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
                ('hash', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='hash', to='ioc_management.hash', to_field='sha256')),
            ],
        ),
    ]
