# Generated by Django 4.2.16 on 2024-12-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0008_alter_hash_sha256_hashreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='md5',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha1',
            field=models.CharField(blank=True, default='none', max_length=40),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha256',
            field=models.CharField(blank=True, default='none', max_length=64, unique=True),
        ),
    ]
