# Generated by Django 5.1.4 on 2025-01-08 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0009_alter_hash_md5_alter_hash_sha1_alter_hash_sha256'),
        ('ioc_management', '0009_codesnippet_alter_hash_md5_alter_hash_sha1_and_more'),
    ]

    operations = [
    ]
