# Generated by Django 4.2.16 on 2025-02-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0011_rename_code_codereview_code_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='validation_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('sospended', 'sospended')], default='new', max_length=32),
        ),
    ]
