# Generated by Django 4.2.16 on 2025-02-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0012_codesnippet_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hash',
            name='validation_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('sospended', 'sospended')], default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='ipadd',
            name='validation_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('sospended', 'sospended')], default='new', max_length=32),
        ),
    ]
