# Generated by Django 5.1.11 on 2025-06-26 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0013_hash_validation_status_ipadd_validation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FQDNAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=32, unique=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True)),
                ('confidence', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=16)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(default=django.utils.timezone.now)),
                ('validation_status', models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('sospended', 'sospended')], default='new', max_length=32)),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FQDNReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(default='none', max_length=64, unique=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
                ('fqdnrw', models.ForeignKey(default='none.com', on_delete=django.db.models.deletion.CASCADE, related_name='fqdnrw', to='ioc_management.fqdnadd', to_field='fqdn')),
            ],
        ),
    ]
