# Generated by Django 4.2.16 on 2025-09-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0014_fqdnadd_fqdnreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(default='none', max_length=64, unique=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
                ('ref_CodeSnippet', models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_CodeSnippet', to='ioc_management.codesnippet', to_field='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='fqdnreview',
            name='fqdnrw',
        ),
        migrations.RemoveField(
            model_name='hashreview',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='ipaddreview',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='vulnreview',
            name='cve_name',
        ),
        migrations.RenameModel(
            old_name='FQDNAdd',
            new_name='FQDN',
        ),
        migrations.DeleteModel(
            name='CodeReview',
        ),
        migrations.DeleteModel(
            name='FQDNReview',
        ),
        migrations.DeleteModel(
            name='HashReview',
        ),
        migrations.DeleteModel(
            name='IpAddReview',
        ),
        migrations.DeleteModel(
            name='VulnReview',
        ),
        migrations.AddField(
            model_name='review',
            name='ref_FQDN',
            field=models.ForeignKey(blank=True, default='none.com', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_FQDN', to='ioc_management.fqdn', to_field='fqdn'),
        ),
        migrations.AddField(
            model_name='review',
            name='ref_Hash',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_Hash', to='ioc_management.hash', to_field='sha256'),
        ),
        migrations.AddField(
            model_name='review',
            name='ref_IpAdd',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_IpAdd', to='ioc_management.ipadd', to_field='ip_address'),
        ),
    ]
