# Generated by Django 4.2.16 on 2025-09-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0015_review_remove_fqdnreview_fqdnrw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ref_FQDN',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_FQDN', to='ioc_management.fqdn', to_field='fqdn'),
        ),
    ]
