# Generated by Django 4.2.16 on 2025-10-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0016_alter_review_ref_fqdn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesnippet',
            options={'verbose_name': '03 :: Code Snippet', 'verbose_name_plural': '03 :: Code Snippets'},
        ),
        migrations.AlterModelOptions(
            name='fqdn',
            options={'verbose_name': '04 :: FQDN', 'verbose_name_plural': '04 :: FQDNs'},
        ),
        migrations.AlterModelOptions(
            name='hash',
            options={'verbose_name': '05 :: File Hash', 'verbose_name_plural': '05 :: File Hashes'},
        ),
        migrations.AlterModelOptions(
            name='ipadd',
            options={'verbose_name': '02 :: IP Address', 'verbose_name_plural': '02 :: IP Addresses'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '06 :: IoC Review', 'verbose_name_plural': '06 :: IoC Reviews'},
        ),
        migrations.AlterModelOptions(
            name='vuln',
            options={'verbose_name': '01 :: Vulnerability', 'verbose_name_plural': '01 :: Vulnerabilities'},
        ),
    ]
