# Generated by Django 4.2.16 on 2025-10-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0017_alter_codesnippet_options_alter_fqdn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='misp_attribute_id',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='misp_attribute_id',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='hash',
            name='misp_attribute_id',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='ipadd',
            name='misp_attribute_id',
            field=models.CharField(blank=True, default='none', max_length=32),
        ),
    ]
