# Generated by Django 4.2.16 on 2025-11-07 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ioc_management', '0018_codesnippet_misp_attribute_id_fqdn_misp_attribute_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Instance Information',
                'verbose_name_plural': 'Instance Information',
            },
        ),
        migrations.AlterModelOptions(
            name='codesnippet',
            options={'ordering': ['-created'], 'verbose_name': '03 :: Code Snippet', 'verbose_name_plural': '03 :: Code Snippets'},
        ),
        migrations.AlterModelOptions(
            name='fqdn',
            options={'ordering': ['-created'], 'verbose_name': '04 :: FQDN', 'verbose_name_plural': '04 :: FQDNs'},
        ),
        migrations.AlterModelOptions(
            name='hash',
            options={'ordering': ['-created'], 'verbose_name': '05 :: File Hash', 'verbose_name_plural': '05 :: File Hashes'},
        ),
        migrations.AlterModelOptions(
            name='ipadd',
            options={'ordering': ['-created'], 'verbose_name': '02 :: IP Address', 'verbose_name_plural': '02 :: IP Addresses'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created'], 'verbose_name': '06 :: IoC Review', 'verbose_name_plural': '06 :: IoC Reviews'},
        ),
        migrations.AlterModelOptions(
            name='vuln',
            options={'ordering': ['-created'], 'verbose_name': '01 :: Vulnerability', 'verbose_name_plural': '01 :: Vulnerabilities'},
        ),
        migrations.RenameField(
            model_name='codesnippet',
            old_name='publish_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='codesnippet',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='publish_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='fqdn',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='hash',
            old_name='publish_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='hash',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='ipadd',
            old_name='publish_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='ipadd',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='publish_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='vuln',
            old_name='publish_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='vuln',
            old_name='update_date',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='misp_attribute_id',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='misp_attribute_id',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='misp_attribute_id',
        ),
        migrations.RemoveField(
            model_name='ipadd',
            name='misp_attribute_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ref_CodeSnippet',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ref_FQDN',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ref_Hash',
        ),
        migrations.RemoveField(
            model_name='review',
            name='ref_IpAdd',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codesnippet', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_codesnippet', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fqdn', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='fqdn',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_fqdn', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='hash',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hash', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='hash',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hash',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_hash', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipadd', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='ip_address',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_ipadd', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='validation_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('suspended', 'suspended')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_review', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulns', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cve',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_vulns', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterModelTable(
            name='codesnippet',
            table='codesnippets',
        ),
        migrations.AlterModelTable(
            name='fqdn',
            table='FQDNs',
        ),
        migrations.AlterModelTable(
            name='hash',
            table='hashes',
        ),
        migrations.AlterModelTable(
            name='ipadd',
            table='ipadds',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
        migrations.AlterModelTable(
            name='vuln',
            table='vulns',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ioc_management.instance')),
                ('lastchange_author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_events', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': '00 :: Event',
                'verbose_name_plural': '00 :: Events',
                'db_table': 'events',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codesnippets', to='ioc_management.event'),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FQDNs', to='ioc_management.event'),
        ),
        migrations.AddField(
            model_name='hash',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashes', to='ioc_management.event'),
        ),
        migrations.AddField(
            model_name='ipadd',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_address', to='ioc_management.event'),
        ),
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ioc_management.event'),
        ),
        migrations.AddField(
            model_name='vuln',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vuln', to='ioc_management.event'),
        ),
    ]
