# Generated by Django 5.2.7 on 2025-12-18 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0019_instance_alter_codesnippet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created_at',), 'verbose_name': '00 :: Event', 'verbose_name_plural': '00 :: Events'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ('name',), 'verbose_name': 'Instance Information', 'verbose_name_plural': 'Instance Information'},
        ),
        migrations.AlterModelOptions(
            name='vuln',
            options={'ordering': ('-created_at',), 'verbose_name': '01 :: Vulnerability', 'verbose_name_plural': '01 :: Vulnerabilities'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='vuln',
            name='created',
        ),
        migrations.RemoveField(
            model_name='vuln',
            name='updated',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vuln',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vuln',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='ioc_management.event'),
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='instance',
            table='instace',
        ),
        migrations.AlterModelTable(
            name='vuln',
            table='vuln',
        ),
    ]
