# Generated by Django 5.2.7 on 2025-12-18 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0019_instance_alter_codesnippet_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesnippet',
            options={'ordering': ('-created_at',), 'verbose_name': '03 :: Code Snippet', 'verbose_name_plural': '03 :: Code Snippets'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created_at',), 'verbose_name': '00 :: Event', 'verbose_name_plural': '00 :: Events'},
        ),
        migrations.AlterModelOptions(
            name='fqdn',
            options={'ordering': ('-created_at',), 'verbose_name': '04 :: FQDN', 'verbose_name_plural': '04 :: FQDNs'},
        ),
        migrations.AlterModelOptions(
            name='hash',
            options={'ordering': ('-created_at',), 'verbose_name': '05 :: File Hash', 'verbose_name_plural': '05 :: File Hashes'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'ordering': ('name',), 'verbose_name': 'Instance Information', 'verbose_name_plural': 'Instance Information'},
        ),
        migrations.AlterModelOptions(
            name='ipadd',
            options={'ordering': ('-created_at',), 'verbose_name': '02 :: IP Address', 'verbose_name_plural': '02 :: IP Addresses'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': '06 :: IoC Review', 'verbose_name_plural': '06 :: IoC Reviews'},
        ),
        migrations.AlterModelOptions(
            name='vuln',
            options={'ordering': ('-created_at',), 'verbose_name': '01 :: Vulnerability', 'verbose_name_plural': '01 :: Vulnerabilities'},
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='created',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='created',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='ipadd',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ipadd',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='vuln',
            name='created',
        ),
        migrations.RemoveField(
            model_name='vuln',
            name='updated',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fqdn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hash',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ipadd',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipadd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vuln',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vuln',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codesnippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_codesnippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='name',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='validation_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('suspended', 'suspended')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fqdns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fqdns', to='ioc_management.event'),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_fqdns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='validation_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('suspended', 'suspended')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='hash',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hash',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_hashes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hash',
            name='platform',
            field=models.CharField(choices=[('linux', 'linux'), ('windows', 'windows'), ('macos', 'macos')], default='windows', max_length=16),
        ),
        migrations.AlterField(
            model_name='hash',
            name='validation_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('suspended', 'suspended')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipadds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipadds', to='ioc_management.event'),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_ipadds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='ioc_management.event'),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='lastchange_author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_vulns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='codesnippet',
            table='codesnippet',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='fqdn',
            table='fqdn',
        ),
        migrations.AlterModelTable(
            name='instance',
            table='instance',
        ),
        migrations.AlterModelTable(
            name='ipadd',
            table='ipadd',
        ),
        migrations.AlterModelTable(
            name='vuln',
            table='vuln',
        ),
    ]
