# Generated by Django 5.2.7 on 2025-12-19 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0020_alter_codesnippet_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='lastchange_author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lastchange_author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='lastchange_author',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='lastchange_author',
        ),
        migrations.RemoveField(
            model_name='ipadd',
            name='lastchange_author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='lastchange_author',
        ),
        migrations.RemoveField(
            model_name='vuln',
            name='lastchange_author',
        ),
        migrations.RemoveField(
            model_name='vuln',
            name='slug',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='contributors_authors',
            field=models.ManyToManyField(editable=False, related_name='contributed_codesnippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='contributors_authors',
            field=models.ManyToManyField(editable=False, related_name='contributed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='contributors_authors',
            field=models.ManyToManyField(editable=False, related_name='contributed_fqdns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hash',
            name='contributors_authors',
            field=models.ManyToManyField(editable=False, related_name='contributed_hashes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipadd',
            name='contributors_authors',
            field=models.ManyToManyField(editable=False, related_name='contributed_ipadds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='contributors_authors',
            field=models.ManyToManyField(editable=False, related_name='contributed_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vuln',
            name='contributors_authors',
            field=models.ManyToManyField(editable=False, related_name='contributed_vulns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
    ]
