# Generated by Django 5.2.7 on 2025-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0021_remove_event_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('bash', 'bash'), ('cmd', 'cmd'), ('powershell', 'powershell'), ('python', 'python')], default='python', max_length=16),
        ),
        migrations.AlterField(
            model_name='hash',
            name='platform',
            field=models.CharField(choices=[('linux', 'linux'), ('macos', 'macos'), ('windows', 'windows')], default='windows', max_length=16),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cvss',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
