# Generated by Django 5.2.7 on 2025-12-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0022_alter_codesnippet_language_alter_hash_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdn',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='hash',
            name='website',
        ),
        migrations.RemoveField(
            model_name='ipadd',
            name='fqdn',
        ),
        migrations.RemoveField(
            model_name='ipadd',
            name='url',
        ),
        migrations.AddField(
            model_name='hash',
            name='url',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='confidence',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='event',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='codesnippets', to='ioc_management.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('bash', 'Bash'), ('cmd', 'CMD'), ('powershell', 'PowerShell'), ('python', 'Python')], default='python', max_length=64),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='validation_status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='confidence',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fqdns', to='ioc_management.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='fqdn',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='validation_status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=64),
        ),
        migrations.AlterField(
            model_name='hash',
            name='confidence',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64),
        ),
        migrations.AlterField(
            model_name='hash',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hashes', to='ioc_management.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hash',
            name='filename',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hash',
            name='md5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hash',
            name='platform',
            field=models.CharField(choices=[('linux', 'Linux'), ('macos', 'MacOS'), ('windows', 'Windows')], default='windows', max_length=64),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hash',
            name='sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hash',
            name='validation_status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='confidence',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=64),
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='event',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ipadds', to='ioc_management.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipadd',
            name='validation_status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='cve',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vuln',
            name='event',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vulns', to='ioc_management.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vuln',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
