# Generated by Django 5.2.7 on 2025-12-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_management', '0023_remove_fqdn_ip_address_remove_hash_website_and_more'),
        ('ioc_management', '0025_remove_exploit_cve_exploit_event_exploit_vuln'),
    ]

    operations = [
    ]
