# Generated by Django 4.2.16 on 2025-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='http_hp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(max_length=32, unique=True)),
                ('req_path', models.CharField(max_length=256, unique=True)),
                ('req_header', models.TextField()),
                ('req_useragent', models.CharField(max_length=256)),
                ('req_xff', models.GenericIPAddressField(unpack_ipv4=True)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
            ],
        ),
    ]
