# Generated by Django 4.2.16 on 2025-09-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='http_hp',
            new_name='http_log',
        ),
    ]
