# Generated by Django 4.2.16 on 2025-09-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_rename_http_hp_http_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='http_log',
            name='req_path',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='http_log',
            name='req_type',
            field=models.CharField(max_length=32),
        ),
    ]
