# Generated by Django 4.2.16 on 2025-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0003_alter_http_log_req_path_alter_http_log_req_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='http_log',
            name='req_body',
            field=models.TextField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='http_log',
            name='req_header',
            field=models.TextField(blank=True, default='none'),
        ),
    ]
