# Generated by Django 4.2.16 on 2025-10-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0004_http_log_req_body_alter_http_log_req_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='telnet_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('req_port', models.IntegerField()),
                ('req_username', models.CharField(max_length=64)),
                ('req_password', models.CharField(max_length=64)),
                ('req_command', models.TextField(blank=True, default='none')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
            ],
            options={
                'verbose_name': '02 :: Telnet Honeypot',
                'verbose_name_plural': '02 :: Telnet Honeypot',
            },
        ),
        migrations.AlterModelOptions(
            name='http_log',
            options={'verbose_name': '01 :: HTTP Honeypot', 'verbose_name_plural': '01 :: HTTP Honeypot'},
        ),
    ]
