# Generated by Django 4.2.16 on 2025-11-07 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0005_telnet_log_alter_http_log_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telnet_log',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
