# Generated by Django 5.2.7 on 2025-12-18 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0006_telnet_log_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('req_body', models.TextField(blank=True, default='none')),
                ('req_header', models.TextField(blank=True, default='none')),
                ('req_path', models.CharField(max_length=256)),
                ('req_type', models.CharField(max_length=32)),
                ('req_useragent', models.CharField(max_length=256)),
                ('req_xff', models.GenericIPAddressField(unpack_ipv4=True)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '01 :: HTTP Honeypot',
                'verbose_name_plural': '01 :: HTTP Honeypot',
                'db_table': 'http_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelnetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default=None, editable=False, max_length=32)),
                ('lastchange_author', models.CharField(default=None, editable=False, max_length=32)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('req_command', models.TextField(blank=True, default='none')),
                ('req_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('req_password', models.CharField(max_length=64)),
                ('req_port', models.IntegerField()),
                ('req_username', models.CharField(max_length=64)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '02 :: Telnet Honeypot',
                'verbose_name_plural': '02 :: Telnet Honeypot',
                'db_table': 'telnet_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='http_log',
        ),
        migrations.DeleteModel(
            name='telnet_log',
        ),
    ]
